M48
; DRILL file {KiCad (6.0.5-0)} date 2022 June 25, Saturday 13:19:07
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-25T13:19:07+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X2.58Y-3.529
X9.68Y-3.529
T2
X6.7024Y-3.708
X6.7024Y-3.908
X6.7024Y-4.408
X7.4Y-3.708
X7.4Y-3.908
X7.4Y-4.408
T0
M30
